jwt:
  encoded-key: L7A/6zARSkK1j7Vd5SDD9pSSqZlqF7mAhiOgRbgv9Smce6tf4cJnvKOjtKPxNNnWQj+2lQEScm3XIUjhW+YVZg==
  normal-encoded-key: bm9ybWFsLWVuY29kZWQta2V5
  ttl-millis: 2592000000  # 30 Days = 3600*1000*24*30

server:
  port: 8080

spring:
  profiles:
    active: dev
  mvc:
    static-path-pattern: /**
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
    converters:
      preferred-json-mapper: fastjson
  # resources:
  #   static-locations: file:/attachments/

mybatis-plus:
  mapper-locations: classpath*:com/jfeat/**/mapping/*.xml
  typeAliasesPackage: com.jfeat.**.model
  global-config:
    id-type: 2  #0:数据库ID自增   1:用户输入id   2:全局唯一id(IdWorker)   3:全局唯一ID(uuid)  4: 该类型为未设置主键类型(none)
    db-column-underline: true
    refresh-mapper: true
    logic-delete-value: -1
    logic-not-delete-value: 1
    #sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: true #配置的缓存的全局开关
    lazyLoadingEnabled: true #延时加载的开关
    multipleResultSetsEnabled: true #开启的话，延时加载一个属性时会加载该对象全部属性，否则按需加载属性
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql语句,调试用

logging:
  level:
    root: INFO
    org.springframework: ERROR
    jdbc.connection: ERROR
    org.apache: ERROR
    com.alibaba: ERROR
    com.jfeat: DEBUG
  #  config: config/logback-spring.xml
  # logback:
  #   rollingpolicy:
  #     # max-file-size: 10MB
  #     file-name-pattern: logs/log.%d{yyyy-MM-dd}.gz
  #     max-history: 90
  # file:
  #   name: logs/access.log
